README.md
docs/commands.md
docs/contributing.md
docs/entities.md
docs/faq.md
docs/typescript.md
npm-shrinkwrap.json
package.json

Not much going on here, just did some cleanup and changes before creating the modules we'll be needing (waiting on confirmation/collaboration of entity relationships).
Changes:
- Cleaned up the `README.md` to be shorter and include only the most relevant information. Updated it to include more important stuff.
- Removed unused dependencies from the `package.json`.
- Upgraded Webpack version for a bug fix.
- Added a `/docs` directory for documentation, and to keep the main `README.md` file concise.
cc @gashcrumb

Cleanup README, add docs, remove unused deps, upgrade Webpack

---

src/app/+testing/forgeCommand.component.ts

Allows you to get through all the pages of ipaas-edit-connector-details for example

Handle multi-step commands properly

---

package.json

Freeze typescript version at 2.1.1

---

src/app/+dashboard/dashboard.spec.ts

Again, hacked my way to this solution - no idea if it's right or not, but it works :)

Fix up dashboard tests

---

circle.yml
config/karma.conf.js
package.json

Following example integration at https://github.com/codecov/example-node

Add codecov.io integration and report via circleci when run

---

src/app/common/loading/loading.component.html

Use patternfly spinner for loading

---

src/app/app.module.ts

Extract paged data from list responses

---

src/config.json

For now, update the config.json to point to the staging instance

Fix URL for now

---

package.json
src/app/app.component.html
src/app/app.component.spec.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/approuting/approuting.module.ts
src/app/approuting/auth-guard.service.ts
src/app/common/common.module.ts
src/app/common/user.model.ts
src/app/common/user.service.spec.ts
src/app/common/user.service.ts
src/app/config.service.ts
yarn.lock

This currently authenticates against OpenShift specified in config file and
only allows access for an authenticated user.
Still have to retrieve user details from the oauth endpoint but that should be
pretty easy.

Enable oAuth login to UI

---

package.json
yarn.lock

`latest` doesn't seem to matter with the yarn.lock file, does it?

Update angular cli

---

.gitignore
angular-cli.json
src/app/connections/connections-routes.module.ts
src/app/connections/connections.module.ts
src/app/connections/list-page/list-page.component.ts
src/app/connections/list/list.component.ts
src/app/integrations/create-page/configure-connection/configure-connection.component.ts
src/app/integrations/create-page/create-page.component.spec.ts
src/app/integrations/create-page/create-page.component.ts
src/app/integrations/create-page/flow-view/flow-view.component.ts
src/app/integrations/create-page/select-connection/select-connection.component.ts
src/app/integrations/integrations.module.ts
src/app/logging.ts
src/app/store/entity/entity.model.ts
src/app/store/entity/entity.store.ts
src/app/store/integration/integration.store.ts
src/polyfills.ts
src/test.ts

Have to run through `ng update` on upgrade and resolve conflicts... fun!
Now linting should work again in CI so be prepared for annoying breaking builds - you'll get used to it though!

Fix up recent ng upgrade

---

src/app/config.service.ts
src/app/integrations/create-page/create-page.component.ts
src/app/store/entity/entity.store.ts
tslint.json

Add lint for console.log, etc calls and fix up linting error

---

.gitignore
.vscode/launch.json
package.json
src/app/app.component.html
src/app/app.component.spec.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/approuting/approuting.module.ts
src/app/approuting/auth-guard.service.ts
src/app/common/user.model.ts
src/app/common/user.service.ts
src/app/config.service.ts
src/config.json
src/config.json.example
src/environments/environment.ts
yarn.lock

This also includes necessary separating out of environment config so we can provide
defaults for development and override at runtime by dropping in separate config file.

[WIP] Add authentication via keycloak

---

package.json
src/app/app.module.ts
src/app/common/common.module.ts
src/app/common/forms.service.ts
src/app/integrations/create-page/configure-connection/configure-connection.component.html
src/app/integrations/create-page/configure-connection/configure-connection.component.ts
src/app/integrations/integrations.module.ts
src/app/store/connection/connection.model.ts
src/app/store/integration/integration.model.ts
yarn.lock

Pulled in `ng2-dynamic-forms` for rendering forms and added a service to convert our form config JSON to the objects it uses, end result:

Add form support and display form on configure connection page

---

circle.yml
karma-xvfb.sh
karma.conf.js
package.json
src/environments/environment.prod.ts
yarn.lock

angular-cli is now @angular/cli so lets upgrade

---

src/app/integrations/create-page/configure-connection/configure-connection.component.html
src/app/integrations/create-page/create-page.component.html
src/app/integrations/create-page/create-page.component.ts
src/app/integrations/create-page/current-flow.service.ts
src/app/integrations/create-page/flow-view/flow-view.component.html
src/app/integrations/create-page/flow-view/flow-view.component.spec.ts
src/app/integrations/create-page/flow-view/flow-view.component.ts
src/app/store/integration/integration.model.ts
src/app/store/integration/integration.store.ts

Saving fails though:
```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "steps" (class com.redhat.ipaas.api.v1.model.Integration$Builder), not marked as ignorable (9 known properties: "kind", "configuration", "users", "integrationTemplateId", "id", "integrationTemplate", "userId", "tags", "name"]) at [Source: io.undertow.servlet.spec.ServletInputStreamImpl@a0d21dd; line: 5, column: 13] (through reference chain: com.redhat.ipaas.api.v1.model.Builder["steps"])
```

More work, try and save the integration too

---

angular-cli.json
package.json
src/app/app.module.ts
src/app/connections/list/list.component.html
src/app/connections/list/list.component.ts
src/app/integrations/integrations.module.ts
src/app/integrations/list-page/list-page.component.spec.ts
src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.scss
src/app/integrations/list/list.component.spec.ts
src/app/integrations/list/list.component.ts
src/app/store/entity/entity.store.ts
yarn.lock

A few points:
- Added AOT-compatible async Toast notifications ([Angular2-Toaster](https://github.com/Stabzs/Angular2-Toaster)).
- Added modal confirmations.
- Styled said modal confirmation.
- Trigger modal confirmations on request to delete integration.
- Trigger Toast notifications on successful delete of integration.
- UI improvements to Integration List.
I'm really sleepy because I ate too many tacos and it's late now, so I didn't add the Toast notifications to creating an integration. It wasn't super clear right away exactly where the create action was, but I did add the notifications to deleting one from the Integration List page. Which, btw, I couldn't get 'delete' to work properly with this store thingy we have. @jimmidyson Is a super duper genius so I'm sure he'll be able to …

Integration List Improvements, Delete Confirmation w/ Modal & Toast

---

src/app/app.component.ts
src/app/common/user.model.ts
src/app/common/user.service.ts

Missed the user model there, this fixes that.

Switch user service over to using generated model

---

src/app/connections/connections-routes.module.ts
src/app/connections/connections.module.ts
src/app/connections/create-page/configure-fields/configure-fields.component.html
src/app/connections/create-page/configure-fields/configure-fields.component.ts
src/app/connections/create-page/connection-basics/connection-basics.component.html
src/app/connections/create-page/connection-basics/connection-basics.component.ts
src/app/connections/create-page/create-page.component.html
src/app/connections/create-page/create-page.component.ts
src/app/connections/create-page/current-connection.ts
src/app/connections/create-page/review/review.component.html
src/app/connections/create-page/review/review.component.ts
src/app/connections/list-toolbar/list-toolbar.component.html
src/app/connections/list-toolbar/list-toolbar.component.ts
src/app/connections/view-page/view-page.component.spec.ts
src/app/connections/view-wrapper/view-wrapper.component.spec.ts
src/app/connections/view/view.component.html
src/app/connections/view/view.component.spec.ts
src/app/connections/view/view.component.ts
src/app/integrations/create-page/current-flow.service.ts
src/app/store/connector/connector.service.ts
src/app/store/connector/connector.store.ts
src/app/store/store.module.ts
src/scss/_common.scss

Given that there's a lot of work here am opening this PR now, don't merge it until I'm ready.
Currently looks like:

Create connection wizard (page 1 and 3 mostly)

---

src/app/integrations/edit-page/edit-page.component.ts
src/app/integrations/integrations.module.ts

mostly trying to figure out a nice way to make the page flow through pages in the integration editor manageable.

Fix create link, also re-use the same array of child routes for editing/creating integrations

---

src/app/integrations/edit-page/current-flow.service.ts
src/app/integrations/edit-page/edit-page.component.html
src/app/integrations/edit-page/edit-page.component.ts
src/app/integrations/edit-page/flow-view/flow-view.component.ts
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.html
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts
src/app/integrations/integrations.module.ts

Just to get the page in place, have yet to wire up the buttons

Stub in the 'save or add step' page

---

angular-cli.json
src/app/app.component.html
src/app/app.component.ts
src/app/connections/create-page/create-page.component.ts
src/app/integrations/edit-page/edit-page.component.ts

Since we got the PR in to show/hide the main nav programatically we can now use this in the create connection and create integration controllers to hide the main nav when the user goes into those pages.

Use nav management functions to show/hide the main nav where appropriate

---

src/app/integrations/edit-page/configure-action/configure-action.component.html
src/app/integrations/edit-page/configure-action/configure-action.component.ts
src/app/integrations/edit-page/current-flow.service.ts
src/app/integrations/edit-page/edit-page.component.ts
src/app/integrations/edit-page/list-actions/list-actions.component.html
src/app/integrations/edit-page/list-actions/list-actions.component.scss
src/app/integrations/edit-page/list-actions/list-actions.component.spec.ts
src/app/integrations/edit-page/list-actions/list-actions.component.ts
src/app/integrations/edit-page/select-action/select-action.component.html
src/app/integrations/edit-page/select-action/select-action.component.ts
src/app/integrations/integrations.module.ts
src/app/integrations/list-toolbar/list-toolbar.component.html
src/app/integrations/list-toolbar/list-toolbar.component.scss
src/app/integrations/list-toolbar/list-toolbar.component.ts

Please don't merge this in yet as it's still a WIP as @gashcrumb and I collaborate on this.

[WIP] re: #202 & #203 Add & Configure Step for Integrations

---

src/app/app.module.ts
src/app/integrations/edit-page/current-flow.service.spec.ts
src/app/integrations/edit-page/current-flow.service.ts
src/app/integrations/list/list.component.ts
src/app/model.ts

Don't merge yet, still working on this, currently updating current-flow.service.ts

Update generated model

---

src/app/integrations/edit-page/edit-page.component.html
src/app/integrations/edit-page/edit-page.component.ts
src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/edit-page/flow-view/flow-view-step.component.scss
src/app/integrations/edit-page/flow-view/flow-view-step.component.ts
src/app/integrations/edit-page/flow-view/flow-view.component.html
src/app/integrations/edit-page/flow-view/flow-view.component.ts

Fix up the flow view so it renders connections/steps properly

---

src/app/integrations/edit-page/action-configure/action-configure.component.ts
src/app/integrations/edit-page/action-select/action-select.component.ts
src/app/integrations/edit-page/connection-select/connection-select.component.html
src/app/integrations/edit-page/connection-select/connection-select.component.ts
src/app/integrations/edit-page/edit-page.component.ts
src/app/integrations/edit-page/flow-view/flow-view-step.component.ts
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.html
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts
src/app/integrations/integrations.module.ts
src/app/integrations/list-toolbar/list-toolbar.component.html
src/app/integrations/list/list.component.html

This drastically simplifies the edit-page.component.ts controller which is awesome.

Use the save or add step page to validate the integration and redirect when needed

---

src/app/connections/list-toolbar/list-toolbar.component.html
src/app/connections/list/list.component.html
src/app/connections/list/list.component.scss
src/app/integrations/edit-page/action-select/action-select.component.html
src/app/integrations/edit-page/action-select/action-select.component.scss
src/app/integrations/edit-page/action-select/action-select.component.ts
src/app/integrations/edit-page/connection-select/connection-select.component.html
src/app/integrations/edit-page/connection-select/connection-select.component.scss
src/app/integrations/edit-page/connection-select/connection-select.component.ts
src/app/integrations/edit-page/edit-page.component.html
src/app/integrations/edit-page/flow-view/flow-view.component.html
src/app/integrations/edit-page/flow-view/flow-view.component.scss
src/app/integrations/edit-page/list-actions/list-actions.component.scss

**NOTE:** Still working on this; please don't merge.
**Changes:**
- Worked on Select an Action, replacing the toolbar for that view w/ functional search bar.
- Cleaned up a bit, styled to better reflect designs.
- Edit Integration field in sidebar no longer looks like a field, per design.
**To Do:**
- Going to do the same things for the Configure Action page.
- Need to update the sidebar to display in progress for both pages as well.

[WIP] re #202 #203 Integration Action Select & Configure

---

src/app/integrations/list-page/list-page.component.html
src/app/integrations/list-page/list-page.component.ts

Fixes the toolbar for the Integration List, so that you can search and sort items properly.
[Screen capture](https://www.useloom.com/share/69d0da2d555a4b73809d096ced16c794)
Why did I take so long to do this? :)

re #214 Fix for Integration List Search & Sort

---

src/app/integrations/edit-page/action-configure/action-configure.component.html
src/app/integrations/edit-page/action-configure/action-configure.component.scss
src/app/integrations/edit-page/action-configure/action-configure.component.ts
src/app/integrations/edit-page/connection-select/connection-select.component.scss
src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/edit-page/flow-view/flow-view-step.component.scss
src/app/integrations/edit-page/flow-view/flow-view-step.component.ts
src/app/integrations/edit-page/flow-view/flow-view.component.html
src/app/integrations/edit-page/flow-view/flow-view.component.scss
src/app/integrations/edit-page/list-actions/list-actions.component.html
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.html
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.scss
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts
src/app/integrations/edit-page/step-configure/step-configure.component.scss
src/app/integrations/edit-page/step-configure/step-configure.component.ts
src/app/integrations/edit-page/step-select/step-select.component.scss
src/app/integrations/edit-page/step-select/step-select.component.ts
src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.ts

Ongoing work for Sprint 9 demo. :)

[WIP] Sprint 9

---

src/app/integrations/edit-page/action-configure/action-configure.component.ts
src/app/integrations/edit-page/connection-select/connection-select.component.ts
src/app/integrations/edit-page/current-flow.service.ts
src/app/integrations/edit-page/step-configure/step-configure.component.html
src/app/integrations/edit-page/step-configure/step-configure.component.ts
src/app/integrations/edit-page/step-select/step-select.component.html
src/app/integrations/edit-page/step-select/step-select.component.ts

With these two pages in place we can now create the sprint target...

Implement the add step and configure step pages

---

src/app/connections/view/view.component.ts
src/app/integrations/edit-page/action-configure/action-configure.component.ts
src/app/integrations/edit-page/step-configure/step-configure.component.ts
src/app/store/step/step.store.ts

This fixes #244 and prepares us for https://github.com/redhat-ipaas/ipaas-rest/pull/171

Get ready to have configuredProperties as an object vs a string

---

src/app/integrations/edit-page/action-configure/action-configure.component.ts
src/app/integrations/edit-page/action-select/action-select.component.ts
src/app/integrations/edit-page/connection-select/connection-select.component.ts
src/app/integrations/edit-page/flow-page.ts
src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/edit-page/flow-view/flow-view-step.component.ts
src/app/integrations/edit-page/flow-view/flow-view.component.html
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts
src/app/integrations/edit-page/step-configure/step-configure.component.ts
src/app/integrations/edit-page/step-select/step-select.component.ts
tslint.json

This refactors the code a bit so integration editor pages share some code.  It also improves the sidebar expander behavior as well as the popover behavior so it's less wonky and horrid :-)
@kahboom FYI

Refactoring

---

src/app/integrations/edit-page/step-select/step-select.component.ts
src/app/store/step/step.store.ts

This adds the filter step to the list, though we've gotta find out what properties are needed for it.

Get the filter stepkind in place for IPAAS-270

---

src/app/integrations/edit-page/flow-view/flow-view-step.component.scss
src/app/integrations/edit-page/flow-view/flow-view-step.component.ts

This fixes #252, needs this PR -> https://github.com/redhat-ipaas/ipaas-ui/pull/271

Create Integration - Disabled sub steps should not have hover state 

---

src/app/integrations/edit-page/current-flow.service.ts
src/app/store/entity/rest.service.ts

Think the way put was getting called wasn't right, giving this a go.  Can't fully test until staging has been updated to accept our PUT preflight request.  Also I suspect the current delete method wasn't right, so trying a different approach there too.

Try and sort #279

---

src/app/integrations/edit-page/flow-view/flow-view.component.scss

Unset the min-height for the flow view which negates #272

---

src/app/integrations/edit-page/flow-view/flow-view-step.component.ts

This fixes the highlighting so that the connection text is only highlighted if you're in it.

Fix connection text highlighting

---

src/app/store/entity/entity.store.ts
src/app/store/step/step.store.ts

This adds the string field for the filter step.  Also added a quick retry for page loading for the odd error back from the API.

Add filter field and also add retries for the odd error back from the API

---

circle.yml
package.json
src/app/app.module.ts
src/app/integrations/edit-page/child-aware-page.ts
src/app/integrations/edit-page/edit-page.component.html
src/app/integrations/edit-page/edit-page.component.ts
src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/edit-page/flow-view/flow-view-step.component.ts
src/app/integrations/edit-page/flow-view/flow-view.component.html
src/app/integrations/edit-page/flow-view/flow-view.component.scss
src/app/integrations/edit-page/flow-view/flow-view.component.ts
src/app/integrations/edit-page/step-configure/data.mapper.example.host.component.ts
src/app/integrations/edit-page/step-configure/step-configure.component.html
src/app/integrations/edit-page/step-configure/step-configure.component.ts
src/app/integrations/integrations.module.ts
src/app/model.ts
yarn.lock

Currently the component shows up, we need data in the integration though to pass along what types are in use.  Also need to add the datamapper endpoint to the config.json file.
@chirino @kcbabo FYI

Datamapper integration

---

.gitignore
.yarnclean
package.json
src/app/app.module.ts
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.html
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts
src/app/model.ts
src/app/store/entity/entity.store.ts
yarn.lock

This shows an error if we get one back on the save or add step page and doesn't exit the integration so you at least have a chance to try saving again :-)
Also regenerate the model so we have updated type definitions.

Add error alert to save or add step page, regenerate model

---

.yarnclean
circle.yml
package.json
yarn.lock

Pull in new datamapper-ui hash

---

src/app/common/forms.service.ts
src/app/store/step/step.store.ts

Add textarea support, tighten up filter config form to match the design better

---

README.md
angular-cli.json
karma.conf.js
package.json
src/app/connections/list/list.component.html
src/app/dashboard/connections.component.html
src/app/dashboard/connections.component.scss
src/app/dashboard/connections.component.ts
src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.spec.ts
src/app/dashboard/dashboard.module.ts
src/app/dashboard/emptystate.component.html
src/app/dashboard/emptystate.component.scss
src/app/dashboard/emptystate.component.ts
src/app/dashboard/integrations.component.html
src/app/dashboard/integrations.component.scss
src/app/dashboard/integrations.component.ts
src/app/integrations/list/list.component.html
src/app/model.ts
yarn.lock

**NOTE**: This is a WIP. Please don't merge yet.
- Add ng2charts & Charts.js.
- Remove kabob.
- Display actual times used for integration.
- Aesthetic changes to reflect designs.
- Update models.
- Resolve some issues, clean up.
**Empty State**
**Non-Empty State**
Don't be afraid of the big donut.. at least it's not Latin..
- Update charts to use real data.
- Display actual labels and dates.
- Use actual status.
- Tooltip for status.

(WIP) Dashboard

---

src/app/connections/view/view.component.html
src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/edit-page/flow-view/flow-view-step.component.ts

Misc fixes, show connector name on page 2 and hide delete icon if a step isn't complete

---

package.json
src/app/integrations/edit-page/step-configure/data.mapper.example.host.component.ts
src/app/integrations/edit-page/step-configure/step-configure.component.ts
yarn.lock

So the UI does show up still, but I've hit two issues/question preventing much more from happening:
https://github.com/redhat-ipaas/datamapper-ui/issues/15
and
https://github.com/redhat-ipaas/datamapper-ui/issues/14

Datamapper update

---

src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.scss

Changed state label/colors to be the following (both here and on the dashboard):
- Active is green
- Deleted is red
- Draft is blue
- Inactive is gray
cc @sjcox-rh @dongniwang

Fix labels in Integration List

---

src/app/dashboard/integrations.component.html
src/app/dashboard/integrations.component.ts

Make the dashboard less of a lie

---

e2e/conf/protractor.base.conf.js
e2e/env.ts

* rename from .js to .ts
This file was accidentally deleted by af1d328c2870b6febbf58c8dceafbf160af5e379.

[restore file] Restore deleted file

---

e2e/connections/list/list.po.ts

[E2E] fix method to count connections in list

---

src/app/integrations/edit-page/current-flow.service.ts
src/app/integrations/edit-page/step-configure/data.mapper.example.host.component.ts
src/app/store/integration-support.service.ts
src/app/store/store.module.ts

This is for https://github.com/redhat-ipaas/ipaas-ui/issues/376

Fetch the integration's POM and give it to the data mapper

---

e2e-xvfb.sh
e2e/conf/protractor.base.conf.js
karma-xvfb.sh

Hi, what do you think about aligning to resolution mentioned by @kahboom in https://github.com/redhat-ipaas/ipaas-ui/pull/369#pullrequestreview-30577532 ?
Example screenshots from cucumber report:

[test] Align screen resolution used in tests to 1280x720

---

package.json
src/app/integrations/edit-page/step-configure/data.mapper.example.host.component.ts
yarn.lock

This makes sure the data mapper component has the right height so the left/right panels scroll individually.

Tweak init logic, set parent container height

---

src/app/connections/list/list.component.spec.ts
src/app/dashboard/dashboard.component.spec.ts
src/app/integrations/integrations.module.ts
src/app/integrations/list-page/list-page.component.spec.ts
src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.spec.ts
src/app/integrations/list/list.component.ts

Fixes https://github.com/redhat-ipaas/ipaas-ui/issues/385 & https://github.com/redhat-ipaas/ipaas-ui/issues/383 and I finally got sick of opening the kebab menu to go into the editor, so fixed that too

Fix #385 and fix #383 and also make the icons/name/description columns go into the editor

---

src/app/connections/list/list.component.spec.ts
src/app/dashboard/dashboard.component.spec.ts
src/app/integrations/edit-page/flow-view/flow-view-step.component.ts
src/app/integrations/integrations.module.ts
src/app/integrations/list-page/list-page.component.spec.ts
src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.spec.ts
src/app/integrations/list/list.component.ts

Fix issue 366

---

src/app/app.module.ts

Hoping this sorts out -> https://github.com/redhat-ipaas/datamapper-ui/issues/23

Initialize typeahead providers which could help redhat-ipaas/datamapper-ui#23

---

src/app/integrations/edit-page/step-configure/data.mapper.example.host.component.ts

Consistent save/load of datamapper data

---

src/app/connections/create-page/create-page.component.html
src/app/connections/create-page/create-page.component.scss
src/app/connections/create-page/create-page.component.ts
src/app/connections/list-toolbar/list-toolbar.component.html
src/app/connections/list/list.component.scss
src/app/connections/view-page/view-page.component.scss
src/app/connections/view-page/view-page.component.ts
src/app/connections/view/view.component.html
src/app/connections/view/view.component.scss
src/app/dashboard/connections.component.html
src/app/dashboard/integrations.component.html
src/app/integrations/edit-page/connection-select/connection-select.component.scss

- Update Create Connection to look more like design.
- Fix bug requiring description.
NOTE: The bottom shows a lighter gray background, which is much better than what was shown before (a white background against all white cards, etc). Arguably, it looks kind of nice. ;) But I'll fix it as soon as I get back later today. Thanks!

Creation Connection Fixes & Improvements

---

e2e/app.po.ts
e2e/common/common.steps.ts
e2e/common/world.ts
e2e/connections/connections.feature
e2e/connections/connections.steps.ts
e2e/connections/edit/edit.po.ts
e2e/narratives/08-first-pass.feature
e2e/narratives/08-first-pass.steps.ts
e2e/tsconfig.json
package.json
yarn.lock

Not ready for merge - opening for discussion about implementation.

Create connection test

---

Caddyfile
yarn.lock

Only try to rewrite requests for pages to default index.html page

---

src/app/integrations/edit-page/edit-page.component.ts
src/app/integrations/edit-page/step-configure/step-configure.component.html
src/app/integrations/edit-page/step-configure/step-configure.component.scss
src/app/integrations/edit-page/step-configure/step-configure.component.ts

Just a quick little fix for the mapper page.

Fix toolbar alignment on data mapper page

---

src/app/connections/create-page/connection-basics/connection-basics.component.html
src/app/connections/create-page/connection-basics/connection-basics.component.ts
src/app/connections/create-page/create-page.component.html
src/app/connections/create-page/create-page.component.scss
src/app/connections/create-page/review/review.component.html
src/app/connections/view/view.component.html
src/app/connections/view/view.component.ts

Rework create connection flow for #365

---

src/app/integrations/edit-page/flow-page.ts
src/app/integrations/edit-page/integration-basics/integration-basics.component.html
src/app/integrations/list/list.component.html

Related to https://github.com/redhat-ipaas/ipaas-rest/issues/277

Use currentStatus instead of desiredStatus for integration list, show spinner when they don't match

---

src/app/dashboard/integrations.component.html
src/app/dashboard/integrations.component.scss
src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.scss

This PR reverts the changes from these two PRs:
https://github.com/redhat-ipaas/ipaas-ui/pull/451
https://github.com/redhat-ipaas/ipaas-ui/pull/449
@kahboom FYI

Revert the flexy stuff

---

src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/edit-page/flow-view/flow-view-step.component.scss

Use the right icons in the integration editor

---

src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/edit-page/flow-view/flow-view-step.component.scss
src/app/integrations/edit-page/flow-view/flow-view-step.component.ts
src/app/integrations/edit-page/flow-view/flow-view.component.scss

Fix styling on mapper page, eliminate skinny donut

---

src/app/dashboard/integrations.component.html
src/app/dashboard/integrations.component.scss
src/app/dashboard/integrations.component.ts
src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.ts

- Update Dashboard colors to reflect agreed upon colors for Integration states.
- Remove deleted Integrations from Integration Board.
- Display actual icons for Integrations in Top 5 Integrations. Adjust padding.
- Update labels for Recent Updates widget.

Fix #482 Update Dashboard colors

---

e2e/common/common.ts

This PR should add option to specify credential via env vars.
Cc @iocanel, sorry took a bit longer due to my PTO.

Load e2e test creadentials from env vars

---

src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.scss

fix #484 Integration List Status Colors

---

src/app/dashboard/integrations.component.html
src/app/dashboard/integrations.component.scss
src/app/dashboard/integrations.component.ts
src/app/integrations/list-toolbar/list-toolbar.component.html
src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.scss

- Vertically align each Integration row in Top 5 Integration widget.
- Fix chart color for Active state to blue.
- Vertically align each Integration row.
- Fix the placeholder text capitalization.

Integration List & Dashboard Minor Changes

---

src/app/dashboard/integrations.component.ts
src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.scss
src/app/integrations/list/list.component.ts

Changes:
- Fix icon padding.
- Center Draft label.
- Add toggle for Active/Inactive.
- Adjust row distribution of elements.
NOTE: Toggle is not reflecting actual Active/Inactive setting. The value is obtained but this is an issue related to the toggle we are using. Fix in next PR.

Integration List

---

src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.scss
src/app/integrations/list/list.component.ts

- Increase width of icon column.
- Add toggles for state.
- Cleanup.
- Fix bug.
- Ah my brain is so fried that I can't remember what I did.

Updates to Integration List

---

.gitignore

I tried to open project in eclipse... :)

[gitignore] Add .tern-project to git ignore

---

src/app/dashboard/integrations.component.scss

Yep, forgot to align my kbabos ;) @kcbabo

Align kbabos on Dashboard! :)

---

src/app/connections/view-page/view-page.component.spec.ts
src/app/connections/view-toolbar/view-toolbar.component.html
src/app/connections/view-toolbar/view-toolbar.component.spec.ts
src/app/connections/view-toolbar/view-toolbar.component.ts
src/app/connections/view-wrapper/view-wrapper.component.html
src/app/connections/view-wrapper/view-wrapper.component.spec.ts
src/app/connections/view-wrapper/view-wrapper.component.ts
src/app/connections/view/view.component.html
src/app/connections/view/view.component.ts

Adds an `Edit` button to the connection view...

Add ability to edit a connection's fields

---

e2e/app.po.ts
e2e/login/login.po.ts

@kahboom @jludvice 
I've happened to redo a login flow in e2e tests again, inherently getting out all async nature of it :). The previous version wasn't very stable for CI to run it properly. Could you please take a look? There might be few more touch ups needed.

e2e: Refactor login flow

---

src/app/dashboard/dashboard.component.html
src/app/dashboard/emptystate.component.html
src/app/dashboard/integrations.component.html
src/app/dashboard/integrations.component.ts
src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/edit-page/flow-view/flow-view.component.html
src/app/integrations/list/list.component.html

Also migrate `<template>` to `<ng-template>`

Fix NPE and rework loading spinner on dashboard

---

e2e/integrations/delete-integrations.feature

Create integration as draft and delete it

[e2e] Test to verify delete action

---

package.json
src/app/app.module.ts
src/app/config.service.ts
src/app/connections/connections.module.ts
src/app/connections/view-page/view-page.component.spec.ts
src/app/connections/view-wrapper/view-wrapper.component.spec.ts
src/app/connections/view/view.component.html
src/app/connections/view/view.component.spec.ts
src/app/connections/view/view.component.ts
src/tsconfig.json
yarn.lock

Reverts syndesisio/syndesis-ui#565

Revert "[WIP] Add ng2-tag-input to implement #564 and #563"

---

package.json
src/app/app.module.ts
src/app/config.service.ts
src/app/connections/connections.module.ts
src/app/connections/view-page/view-page.component.spec.ts
src/app/connections/view-wrapper/view-wrapper.component.spec.ts
src/app/connections/view/view.component.html
src/app/connections/view/view.component.spec.ts
src/app/connections/view/view.component.ts
src/tsconfig.json
yarn.lock

Reverts syndesisio/syndesis-ui#566
@kahboom can you maybe not merge this?  :-)

Add ng2-tag-input to implement #564 and eventually #563

---

pom.xml

I'd like to add a pom to do the yarn/angular-cli build so that we can build a little easier in Jenkins.   Does this look okay?

Add a pom for installing yarn/angular-cli / building.

---

README.md

Update the links to contributing to point to the syndesis website.

chore(documentation): Update README.md

---

src/environments/environment.ts

related to #609 (don't think this actually fixes it though)

chore((configuration)): Update environments.ts with the changes applied to config.json.example

---

src/app/common/forms.service.ts

fix(forms): Use `hint` not `placeholder` for element descriptions

---

src/app/connections/list/list.component.html
src/app/connections/list/list.component.scss

Take out the overflow: hidden property so the menu shows up
Fixes #574

fix(connections): Tweak the menu styling

---

src/app/integrations/edit-page/step-configure/step-configure.component.ts

Also run prettier on step-configure.component.ts
fixes #621

fix(step-configure): Fix the data mapper view

---

src/app/common/forms.service.ts

fix(forms): Fix checkbox alignment

---

src/app/store/step/step.store.ts

fix(step store): add filter back as 'advanced filter'

---

src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.html
src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.scss
src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.ts
src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.model.ts
src/app/integrations/edit-page/step-configure/step-configure.component.html
src/app/integrations/edit-page/step-configure/step-configure.component.ts
src/app/integrations/edit-page/step-select/step-select.component.ts

Some changes being made to the Basic Filter. One relevant issue here: #623
Remaining Items:
Nice-to-haves:

(WIP) Basic Filter Updates

---

package.json
src/app/app.component.html
src/app/approuting/approuting.module.ts
src/app/common/common.module.ts
src/app/common/list-expansion/list-expansion.component.html
src/app/common/list-expansion/list-expansion.component.ts
src/app/common/list-view-rows/list-view-rows.component.html
src/app/common/list-view-rows/list-view-rows.component.ts
src/app/common/toolbar/list-toolbar.component.html
src/app/common/toolbar/list-toolbar.component.scss
src/app/common/toolbar/list-toolbar.component.ts
src/app/settings/oauth-clients/oauth-clients.component.html
src/app/settings/oauth-clients/oauth-clients.component.ts
src/app/settings/settings-root.component.html
src/app/settings/settings-root.component.ts
src/app/settings/settings.module.ts
yarn.lock

First spike, also kicked off a re-usable list toolbar widget that's WIP.

WIP - Global Settings Page

---

src/app/integrations/edit-page/edit-page.component.ts

Removes calls to hide/show the main menu while I figure out what change in patternfly caused this
affects #638

fix(integration editor): Temp tweak to avoid API change

---

src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.model.ts

Until we load the options properly.

fix(basic-filter): Remove prefix button

---

src/app/connections/create-page/create-page.component.ts

fix(connections): Quick tweak to avoid NPE

---

pom.xml
src/assembly/unix-dist.xml

This assembly will wrap up the dist and config file as a zip & tar.gz, this will be changed to suite the nginx image, rather than caddy

ENTESB-6991 Create zip for use in OSBS

---

src/app/app.component.html
src/app/app.component.spec.ts
src/app/app.module.ts

fix(auth): Notification toast when refresh token fails

---

src/app/integrations/list/list.component.ts

fix(integrations): Remove `Pending` restriction on delete

---

src/app/connections/list/list.component.html
src/app/connections/view-page/view-page.component.html
src/app/connections/view-page/view-page.component.ts
src/app/connections/view-wrapper/view-wrapper.component.html
src/app/connections/view-wrapper/view-wrapper.component.ts

fix(connections): Add edit menu item to kebab

---

src/app/settings/oauth-apps/oauth-app-form.component.html
src/app/settings/oauth-apps/oauth-app-form.component.ts
src/app/settings/oauth-apps/oauth-app-modal.component.html
src/app/settings/oauth-apps/oauth-app-modal.component.ts
src/app/settings/oauth-apps/oauth-apps.component.html
src/app/settings/oauth-apps/oauth-apps.component.ts
src/app/settings/settings.module.ts

Finish up the oauth settings with a modal prompt for removing credentials
fixes #546

feat(settings): Finish up with modal prompt

---

src/app/integrations/edit-page/current-flow.service.ts
src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.html
src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.ts
src/app/integrations/edit-page/step-configure/step-configure.component.html
src/app/integrations/edit-page/step-configure/step-configure.component.ts
src/app/store/integration-support.service.ts

Had @gashcrumb review with me, we're unsure why but it still results in a 500 error. See screenshot below.
Of course please ignore the browser logs (removed from the code).

re #630 Filter Options URL Fix

---

src/app/app.component.html
src/app/app.component.ts

fix(auth): Prevent duplicated expired session toast notifications

---

src/app/integrations/edit-page/action-configure/action-configure.component.ts

fix(integrations): Reset page when the position sub fires

---

src/app/integrations/edit-page/current-flow.service.spec.ts
src/app/integrations/edit-page/current-flow.service.ts

feat(integrations): Add additional convenience methods

---

src/app/connections/view/view.component.ts

fix(connections): Strip out null/empty values when validating

---

src/app/integrations/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
src/app/integrations/integrations.module.ts

Also more intelligently grabs previous and subsequent connections out of the integration
fixes #604

feat(data-mapper): Pass multiple source to datamapper if available

---

src/app/integrations/edit-page/flow-view/flow-view.component.html
src/app/integrations/edit-page/flow-view/flow-view.component.ts

Makes the input field for the name editable again
Fixes #661

fix(integrations): Bring back proper name editing

---

angular-cli.json
package.json
src/app/app.component.html
src/app/app.component.spec.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/common/common.module.ts
src/app/connections/connections.module.ts
src/app/connections/list-page/list-page.component.spec.ts
src/app/connections/list/list.component.html
src/app/connections/list/list.component.spec.ts
src/app/connections/list/list.component.ts
src/app/connections/view-page/view-page.component.spec.ts
src/app/connections/view-wrapper/view-wrapper.component.spec.ts
src/app/connections/view/view.component.spec.ts
src/app/dashboard/dashboard.component.spec.ts
src/app/dashboard/dashboard.module.ts
src/app/dashboard/integrations.component.ts
src/app/integrations/edit-page/edit-page.component.spec.ts
src/app/integrations/edit-page/list-actions/list-actions.component.html
src/app/integrations/edit-page/list-actions/list-actions.component.spec.ts
src/app/integrations/edit-page/list-actions/list-actions.component.ts
src/app/integrations/integrations.module.ts
src/app/integrations/list-page/list-page.component.spec.ts
src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.spec.ts
src/app/integrations/list/list.component.ts

refactor(toast): Use patternfly-ng toast notification component

---

src/app/connections/create-page/configure-fields/configure-fields.component.html
src/app/connections/create-page/configure-fields/configure-fields.component.ts
src/app/connections/create-page/connection-basics/connection-basics.component.ts
src/app/connections/create-page/current-connection.ts
src/app/store/connector/connector.service.ts
src/app/store/connector/connector.store.ts

Currently just fetches the data and stores it, next step is figure out what to do with it
relates to #556

feat(connections): fetch credentials from API when user selects connector

---

src/app/dashboard/dashboard.component.spec.ts
src/app/dashboard/dashboard.module.ts
src/app/dashboard/integrations.component.html
src/app/integrations/actions/actions.component.html
src/app/integrations/actions/actions.component.spec.ts
src/app/integrations/actions/actions.component.ts
src/app/integrations/actions/actions.module.ts
src/app/integrations/integrations.module.ts
src/app/integrations/list-page/list-page.component.spec.ts
src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.spec.ts
src/app/integrations/list/list.component.ts

Share the same actions dropdown across integrations list and dashboard integrations list. Fixes #579

fix(integrations): build syndesis-integration-actions component

---

pom.xml

Need to add developer and scm information to pom for Nexus staging checks.

Add developer and scm information to pom.

---

package.json
src/app/app.component.spec.ts
src/app/app.component.ts
src/app/common/common.module.ts
src/app/common/navigation.service.ts
src/app/connections/create-page/create-page.component.ts
src/app/integrations/edit-page/edit-page.component.spec.ts
src/app/integrations/edit-page/edit-page.component.ts
yarn.lock

Provides functions to show and hide the main navigation, also this commit updates patternfly so
@syndesisio/ui-api run `yarn install` after merging and restart your dev instance.
fixes #651 relates to #702 #687 #658 #638 #669

feat(common): Add a nav service

---

src/app/app.module.ts
src/app/integrations/edit-page/action-configure/action-configure.component.html
src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.html
src/app/integrations/edit-page/step-configure/step-configure.component.html
src/app/integrations/integrations.module.ts
src/app/settings/settings.module.ts

refactor(form): Update all modules to use PatternFly form UI module

---

src/app/connections/create-page/configure-fields/configure-fields.component.html
src/app/connections/create-page/configure-fields/configure-fields.component.ts
src/app/connections/create-page/create-page.component.ts
src/app/connections/view/view.component.html

doesn't yet do anything
related to #556

feat(connections): Get the oauth button showing for starters

---

src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.ts
src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.model.ts

Switch to a function that returns the model (fixes #654) and also use a home-grown findById function
to locate objects in the filter model.
fixes #631 and fixes #654

fix(integrations): Use a home-grown findById for our model

---

src/app/connections/list/list.component.html
src/app/integrations/edit-page/list-actions/list-actions.component.html
src/app/integrations/edit-page/step-select/step-select.component.html
src/app/integrations/list/list.component.html

refactor(selectors): Add dom classes and attributes to ease up e2e tests

---

Caddyfile

fix(caddy): Fix incorrect rewrite rule causing 301 redirect rather than internal rewrite

---

src/app/app.component.html
src/app/common/capitalize.pipe.ts
src/app/common/common.module.ts
src/app/common/titleize.pipe.ts
src/app/integrations/edit-page/action-configure/action-configure.component.html
src/app/integrations/edit-page/action-configure/action-configure.component.ts
src/app/integrations/edit-page/action-select/action-select.component.html
src/app/integrations/edit-page/connection-select/connection-select.component.html
src/app/integrations/edit-page/connection-select/connection-select.component.ts
src/app/integrations/edit-page/flow-page.ts
src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.html
src/app/integrations/edit-page/step-configure/step-configure.component.html
src/app/integrations/edit-page/step-select/step-select.component.html

Updates the breadcrumbs in the integration editor for #704, Change the Next button to Done for #684.
Adds simple titlize and ccapitalize pipes.  Adds misc tweaks to the connection selectino page
fixes #704, fixes #684

feat(integrations): Overhaul breadcrumbs

---

src/app/integrations/edit-page/step-configure/data-mapper/data-mapper-host.component.ts

Just noticed it when working in the area

fix(integrations): Fix error handling when pom.xml fetch fails

---

src/app/connections/view/view.component.html
src/app/connections/view/view.component.ts

Reverts syndesisio/syndesis-ui#720
fixes https://github.com/syndesisio/syndesis-ui/issues/726
reopens #668

Revert "fix(connection): Connection fields in edit form are not in sync with …"

---

src/app/integrations/edit-page/flow-view/flow-view-step.component.ts
src/app/integrations/edit-page/step-configure/step-configure.component.html
src/app/integrations/edit-page/step-configure/step-configure.component.ts
src/app/integrations/edit-page/step-select/step-select.component.ts
src/app/store/step/step.store.ts

relates to syndesisio/syndesis-rest#451

fix(integrations): Switch stepKind from basic-filter to rule-filter

---

src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/edit-page/flow-view/flow-view-step.component.ts
src/app/integrations/edit-page/step-select/step-select.component.ts
src/app/store/step/step.store.ts

Take out some local hacks in the step related controllers an makes the step store the source of
names and descriptions

refactor(integrations): Take out some hacks

---

src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.ts
src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.model.ts
src/app/integrations/edit-page/step-configure/step-configure.component.html
src/app/integrations/edit-page/step-configure/step-configure.component.ts
src/app/store/step/step.store.ts

fix(integrations): Load basic filter form data from step

---

src/app/connections/create-page/configure-fields/configure-fields.component.ts
src/app/connections/create-page/current-connection.ts
src/app/store/connector/connector.service.ts
src/app/store/connector/connector.store.ts

Relates to https://github.com/syndesisio/syndesis-ui/issues/556

feat(connections): Make first call to acquire oauth credentials

---

src/app/connections/create-page/current-connection.ts
src/app/store/connector/connector.service.ts

feat(connections): Set the cookie and do the redirect

---

src/app/integrations/edit-page/flow-page.ts
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.html
yarn.lock

fix(integrations): Update buttons on save or add step page

---

src/app/settings/oauth-apps/oauth-apps.component.html
src/app/settings/oauth-apps/oauth-apps.component.scss

fix(settings): Increase specificity for toolbar override

---

src/app/integrations/edit-page/current-flow.service.ts
src/app/integrations/edit-page/flow-view/flow-view.component.html
src/app/integrations/edit-page/flow-view/flow-view.component.ts
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts

fix(integrations): fix empty tooltip and do a little refactoring

---

src/app/app.component.html
src/app/common/modal/modal.component.html
src/app/connections/list/list.component.html
src/app/dashboard/integrations.component.html
src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/list/list.component.html
src/app/settings/oauth-apps/oauth-app-modal.component.html

fix(modals): Change modals buttons to be in line with PatternFly design

---

src/app/connections/create-page/create-page.component.ts

fix(connection): Fix buttons page 2 create connection. Fixes #707

---

src/app/integrations/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
src/app/store/connector/connector.service.ts

fix data mapper host component getting invalid CORS request, use a relative URL for OAuth redirect

fix(misc): Misc fixes

---

src/app/integrations/edit-page/current-flow.service.ts
src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.model.ts

relates to syndesisio/syndesis-rest#451

feat(integrations): Use a hatchet on configuredProperties values for now

---

src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.ts
src/app/integrations/edit-page/step-configure/step-configure.component.ts

fix(integration): fix invalid values in Basic Filter Steps

---

src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.html
src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.ts
src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.model.ts
src/app/integrations/edit-page/step-configure/filter-steps/filter.interface.ts

Set ops and paths on the appropriate form fields
fixes #637

feat(integrations): Pull form data from server

---

src/app/integrations/edit-page/current-flow.service.ts

Enrich the stepKind if the step has filterExpression on it
@rhuss FYI

fix(integrations): insert square bolt into round hole

---

src/app/integrations/edit-page/current-flow.service.ts

fix(integrations): filter out null steps, delete filterExpression from step

---

src/app/connections/view-toolbar/view-toolbar.component.html
src/app/connections/view/view.component.html

feat(connections): Hide form if connection used oauth flow

---

src/app/integrations/edit-page/action-select/action-select.component.ts

fix(integration): Fix error: Attempt to use a destroyed view

---

src/app/integrations/edit-page/flow-view/flow-view.component.html
src/app/integrations/edit-page/flow-view/flow-view.component.scss
src/app/integrations/edit-page/flow-view/flow-view.component.ts

Use inline templates instead of copypasta, fix up CSS so it's a bit more clear
fixes #774 and relates to #765

fix(integrations): rework insert step lines a bunch

---

src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/edit-page/flow-view/flow-view-step.component.ts

fix(integrations): disallow default popover triggers

---

src/app/integrations/detail-page/detail.component.html
src/app/integrations/detail-page/detail.component.scss
src/app/integrations/detail-page/detail.component.ts

lay out page, add controls, add dummy history data, render integration view
fixes #786
related to syndesisio/syndesis-project#22

feat(integrations): Stub out the integration detail page

---

src/app/integrations/edit-page/action-select/action-select.component.html
src/app/integrations/edit-page/action-select/action-select.component.ts

fix(integrations): rework page logic a bit

---

src/app/connections/view/view.component.html
src/app/connections/view/view.component.ts
src/app/store/connection/connection.service.ts

feat(connection): add connection name taken validation

---

src/app/integrations/components/integrationViewBase.component.ts
src/app/integrations/components/status.component.scss
src/app/integrations/components/status.component.ts
src/app/integrations/detail-page/detail.component.html
src/app/integrations/detail-page/detail.component.ts
src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.scss
src/app/integrations/list/list.component.spec.ts
src/app/integrations/list/list.component.ts
src/app/integrations/list/list.module.ts
src/app/store/integration/integration.store.ts

also move calls to change integration state into the store, take out a bunch of setTimeouts too
relates to #795

feat(integrations): Pull out status into separate component

---

src/app/connections/create-page/create-page.component.ts
src/app/store/connector/connector.service.ts

refactor(connection): Use document hash rather than QueryParam

---

proxy.conf.js

fix(dev): Default api base and warn if it's not set

---

src/app/common/common.module.ts
src/app/common/editable.component.ts
src/app/integrations/detail-page/detail.component.html
src/app/integrations/detail-page/detail.component.scss
src/app/integrations/detail-page/detail.component.ts

feat(integrations): Add editable property component and use it

---

src/app/connections/create-page/create-page.component.ts

fix(connection): Fix bug in connection creation workflow

---

.circleci/config.yml
src/app/app.component.html
src/app/app.component.ts
src/app/app.module.ts

Changes:
- Fixed the CircleCI project name referenced in `.circle/config.yml`.
- Very, very basic docs, but it's a start. :)

Fix CircleCI Config & Add Docs

---

src/app/integrations/edit-page/common/cancel-add-step.component.spec.ts
src/app/integrations/edit-page/common/cancel-add-step.component.ts
src/app/integrations/edit-page/step-configure/step-configure.component.ts

fix(integrations): cancel doesn't always delete the step

---

src/app/integrations/edit-page/action-configure/action-configure.component.html
src/app/integrations/edit-page/action-select/action-select.component.html
src/app/integrations/edit-page/action-select/action-select.component.ts

feat(integrations): show the connection name in the title

---

src/app/common/ui-patternfly/list-toolbar/list-toolbar.component.html
src/app/common/ui-patternfly/list-toolbar/list-toolbar.component.ts
src/app/connections/list-page/list-page.component.html
src/app/integrations/list-page/list-page.component.html

feat(common): Add a viewTemplate input

---

src/app/common/ui-patternfly/list-toolbar/list-toolbar.component.scss
src/app/connections/list-page/list-page.component.scss
src/app/integrations/list-page/list-page.component.scss

feat(integrations, connections): Fixed position toolbar on list pages

---

src/app/common/editable/editable-tags.component.ts
src/app/common/editable/editable-text.component.ts
src/app/common/editable/editable-textarea.component.ts
src/app/common/editable/editable.component.spec.ts
src/app/common/editable/editable.component.ts
src/app/integrations/detail-page/detail.component.html
src/app/integrations/detail-page/detail.component.ts

feat(editable-*.component): add support to validation

---

src/app/integrations/edit-page/step-configure/step-configure.component.ts

fix(integrations): Fix NPE on step configure page

---

src/app/integrations/edit-page/current-flow.service.ts
src/app/integrations/edit-page/flow-page.ts
src/app/store/entity/entity.store.ts

fix(integrations): Make update return the entity

---

src/app/common/modal/modal.component.ts
src/app/integrations/edit-page/current-flow.service.ts
src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/edit-page/flow-view/flow-view-step.component.ts
src/app/integrations/edit-page/flow-view/flow-view.component.ts

fix(integrations, common): Update the registered modal ID if it changes

---

src/app/integrations/detail-page/detail.component.html

fix(integrations): use btn-danger for delete button

---

src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/edit-page/flow-view/flow-view-step.component.scss

fix(integrations): move the trash icon over, add a tooltip too

---

src/app/integrations/edit-page/flow-view/flow-view-step.component.ts

fix(integrations): Check the result property on the modal object

---

src/app/common/loading/loading.component.html
src/app/integrations/detail-page/detail.component.html
src/app/integrations/detail-page/detail.component.ts
src/app/integrations/edit-page/action-configure/action-configure.component.html
src/app/integrations/edit-page/action-configure/action-configure.component.ts
src/app/integrations/edit-page/action-select/action-select.component.html
src/app/integrations/edit-page/action-select/action-select.component.ts
src/app/integrations/edit-page/connection-select/connection-select.component.html
src/app/integrations/edit-page/connection-select/connection-select.component.ts
src/app/integrations/edit-page/current-flow.service.ts
src/app/integrations/edit-page/edit-page.component.html
src/app/integrations/edit-page/edit-page.component.ts
src/app/integrations/edit-page/flow-page.ts
src/app/integrations/edit-page/flow-view/flow-view-step.component.ts
src/app/integrations/edit-page/flow-view/flow-view.component.html
src/app/integrations/edit-page/flow-view/flow-view.component.ts
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.html
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts
src/app/integrations/edit-page/step-configure/step-configure.component.html
src/app/integrations/edit-page/step-configure/step-configure.component.ts
src/app/integrations/edit-page/step-select/step-select.component.html
src/app/integrations/edit-page/step-select/step-select.component.ts
src/app/integrations/edit-page/step-select/step-visible.pipe.ts

Editor loading refactor (major surgery)

---

package.json
src/app/integrations/components/integrationViewBase.component.ts
src/app/integrations/list/list.component.ts
yarn.lock

chore(patternfly): Upgrade patternfly-ng to version 0.9.2

---

src/app/integrations/edit-page/action-configure/action-configure.component.ts

Just a quick patch to prevent the NPE.
Fixes #876

fix(actions): Quick fix for actions not having any properties or steps

---

src/app/connections/create-page/create-page.component.ts
src/app/connections/create-page/current-connection.ts
yarn.lock

fix(connections): ensure current connection service's state is reset

---

src/app/connections/create-page/current-connection.ts

fix(connection): Fix issue #883

---

package.json
yarn.lock

fix(integrations): Update data mapper

---

src/app/connections/detail-page/detail-page.component.ts
src/app/connections/detail-page/info.component.ts

feat(connection): add labels to tags and description in connection details page

---

src/app/connections/create-page/configure-fields/configure-fields.component.html
src/app/connections/create-page/create-page.component.html

feat(connection): Change text in Create Connection pages to make it easier for user

---

src/app/common/forms.service.ts
src/app/integrations/edit-page/action-configure/action-configure.component.html
src/app/integrations/edit-page/action-configure/action-configure.component.ts
src/app/integrations/edit-page/child-aware-page.ts
src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/edit-page/flow-view/flow-view-step.component.ts
src/app/integrations/integrations.module.ts
yarn.lock

Adds an additional page index to the action config page used to key into the propertyDefinitionSteps
attribute
relates to #868

feat(integrations): Add more support for multi-step action config

---

src/app/connections/create-page/current-connection.ts

feat(connections): Add the connector ID as a tag to all new connections

---

src/app/integrations/edit-page/flow-view/flow-view-step.component.ts

fix(integrations): avoid NPE

---

src/app/integrations/edit-page/edit-page.component.ts
src/app/integrations/edit-page/step-select/step-select.component.ts

fix(integrations): Catch updates to the route properly

---

src/app/app.component.html

fix(app): avoid doing a GET to /null

---

src/app/integrations/edit-page/action-configure/action-configure.component.ts
src/app/store/integration-support.service.ts

Doesn't do anything with the response yet except logs it (or errors)
@zregvart CC
relates to #868

feat(integrations): invoke on metadata service on the action configure page

---

src/app/common/forms.service.ts
src/app/common/ui-patternfly/syndesis-form-control.component.html
src/app/common/ui-patternfly/syndesis-form-control.scss
src/app/connections/common/configuration/configuration.service.ts
src/app/connections/common/configuration/validation.component.html
src/app/connections/common/configuration/validation.component.ts
src/app/connections/connections.module.ts
src/app/connections/create-page/configure-fields/configure-fields.component.html
src/app/connections/create-page/configure-fields/configure-fields.component.spec.ts
src/app/connections/create-page/configure-fields/configure-fields.component.ts
src/app/connections/detail-page/configuration.component.html
src/app/connections/detail-page/configuration.component.ts
src/app/connections/detail-page/info.component.ts
src/app/connections/view/view.component.html
src/app/integrations/list-page/list-page.component.spec.ts
src/app/integrations/list/list.component.spec.ts

fix(connection): validate Configure Connection form (step 2 of create connection)

---

src/app/app.component.html
src/app/app.component.ts

fix(app): Add top logo back in

---

src/app/integrations/edit-page/action-configure/action-configure.component.ts

fix(integrations): ensure any error is properly shown somehow

---

src/app/connections/create-page/configure-fields/configure-fields.component.ts
src/app/connections/create-page/create-page.component.html
src/app/connections/create-page/create-page.component.ts
src/app/connections/create-page/review/review.component.html
src/app/connections/create-page/review/review.component.spec.ts
src/app/connections/create-page/review/review.component.ts
src/app/connections/detail-page/info.component.ts
src/app/connections/view/view.component.ts
src/app/store/connection/connection.service.ts

fix(connection): Fix validation on step 3 of create connection wizard

---

src/app/integrations/edit-page/step-select/step-select.component.html

fix(integrations): rework step select text

---

src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.html

fix(integrations): update basic filter text

---

src/app/common/forms.service.ts

relates to #949 
@akieling @zregvart FYI

feat(forms): Use the enum value as typeahead

---

src/app/integrations/detail-page/detail.component.html
src/app/integrations/detail-page/detail.component.ts
src/app/store/entity/entity.store.ts

feat(integrations): connect the buttons on the detail page

---

src/app/common/ui-patternfly/syndesis-form-control.component.html

feat(common): Show tooltip icon for checkboxes

---

src/app/store/entity/events.service.ts

feat(events): Handle disconnects via reconnect attempts

---

src/app/app.component.html

feat(app): hide db dev menu

---

src/app/connections/create-page/connection-basics/connection-basics.component.html
src/app/connections/list/list.component.html
src/app/connections/list/list.component.ts
src/app/dashboard/connections.component.html
src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.ts
src/app/dashboard/integrations.component.html
src/app/dashboard/integrations.component.ts
src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.ts
src/app/store/entity/entity.store.ts
src/scss/_overrides.scss

fix(app): Ensure empty state is in sync with the designs

---

src/app/store/step/step.store.ts

fix(store): Take out pretend step kinds

---

package.json
yarn.lock

fix(datamapper): Error message for conversion are stacking up

---

src/app/common/common.module.ts
src/app/common/derp.pipe.ts
src/app/integrations/edit-page/action-select/action-select.component.html
src/app/integrations/edit-page/action-select/action-select.component.scss
src/app/integrations/edit-page/action-select/action-select.component.ts
src/app/integrations/edit-page/list-actions/list-actions.component.html
src/app/integrations/edit-page/list-actions/list-actions.component.ts

refactor(actions): Use common toolbar for actions list filtering

---

src/app/settings/settings-root.component.html

fix(settings): Remove "placeholder" item from settings tabs

---

src/app/common/editable/editable-tags.component.ts
src/app/connections/create-page/review/review.component.html

fix(tag-input): set comma as another tag separator key and add key on blur

---

src/app/app.component.ts
src/config.json.example
src/config.json.minishift
src/config.json.staging
src/index.html

feat(app): add override for touch icon too

---

src/app/integrations/edit-page/action-configure/action-configure.component.html

feat(integrations): Add a button back to the action select page

---

src/app/setup/github-oauth.component.html
src/app/setup/github-oauth.component.scss
src/app/setup/github-oauth.component.ts

Still a WIP, need to do the plumbing for the API and some UI aesthetic changes and logic, but it looks like this for now. I think we can merge in soon enough because there is no direct access to this page for now.
Outstanding:
- Collapse sections when they are completed (var currently exists).
- Style according to completed or not.
- Send HTTP requests to GH API. Maybe store locally, not sure if we'll have time for this.

WIP #952 GitHub OAuth

---

src/app/integrations/edit-page/current-flow.service.ts

fix(integrations): current flow log output to debug

---

.circleci/config.yml
package.json
src/app/common/ui-patternfly/list-toolbar/list-toolbar.component.ts
src/app/integrations/detail-page/detail.component.html
src/app/integrations/list-page/list-page.component.html

fix(integrations): hide tags from integrations until fleshed out

---

src/app/settings/oauth-apps/oauth-app-form.component.html

fix(settings): Fix capitalisation in success notification

---

src/scss/_overrides.scss

fixes syndesisio/syndesis-project#109

fix(app): Fix nav heading in firefox

---

src/app/settings/oauth-apps/oauth-apps.component.html
src/app/settings/oauth-apps/oauth-apps.component.ts

fix(settings): Use branding rather than hard-coded app name

---

src/app/app.module.ts

Rm GH auth stuff

---

src/app/integrations/edit-page/current-flow.service.ts

fix(integrations): only log the integration to debug

---

src/app/integrations/detail-page/detail.component.ts

fix(integrations): hide `Deploy` button for the current revision

---

src/app/store/step/step.store.ts
yarn.lock

Fix #1065 
Steps of kind "none" shouldn't be considered.

fix(integration): Fix error preventing datamapper from loading

---

src/app/integrations/edit-page/action-configure/action-configure.component.ts

Problem: when configuring action properties some of the properties might
depend on previously defined properties, i.e. for Invoke SQL Stored
procedure action `template` parameter depends on `procedureName`
parameter, those properties might end up unset if they are not in in a
step that is one step behind the action property they depend on. This
does not allow for dependencies between properties for actions that have
single step definition.
Solution: set all action property values that are `null` to the
`defaultValue` fetched from metadata endpoint at the point where all
other properties should be defined, i.e. when processing `continue`
handler.

fix: set unset action properties to their default values at the end of action definition

---

src/app/connections/list/list.component.html

fix(integrations): hide new connection tile if there's no connections

---

src/app/integrations/list/list.component.scss

fix(integrations): fix icon layout on edge in integration list

---

src/app/settings/settings-root.component.html

Remove 'My Account' tab from Settings page.
fixes #1070

feat(settings): Remove 'My Account' tab

---

src/app/common/forms.service.ts

@zregvart FYI
relates to #1088

fix(common): fix up layout for select control

---

src/app/app.component.html

Removing this until we have the build version and other details in place and accessible in the
distro.
fixes #1069

fix(about): Remove About from navigation bar

---

src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.html
src/app/integrations/edit-page/step-configure/step-configure.component.html
src/app/integrations/edit-page/step-configure/step-configure.component.scss

fix(integrations): make step-configure body overflow:visible

---

pom.xml

Update the yarn/node versions and clean the node_modules in the pom.xml to match what the circle build does.

Upgrade yarn version, clean node_modules to match circle build.

---

.dockerignore

Otherwise symlink is not properly created

fix(docker): Ensure any config.json in the dist dir is not included in the Docker image

---

package.json

build(tests): Ignore sourcemaps when testing

---

src/app/app.component.html
src/app/app.component.scss
src/app/app.component.ts
src/app/common/common.module.ts
src/app/common/user.service.ts
src/app/dashboard/integrations.component.ts

Changes:
- Add method to `userService` and call from the `AppComponent`.
- Remove reference to `oauthService`.
- Add Logout to dropdown menu.
- Use new logout endpoint to make direct HTTP call.
- Add toast notification to confirm success/failure of logout request.
Outstanding:
- Need to know what the payload for the HTTP POST request should be for the new logout endpoint `/oauth/sign_out`. cc @jimmidyson 
Former PR: https://github.com/syndesisio/syndesis-ui/pull/1091
fix #1035

feat(logout): Support for Logout

---

README.md

Improved quickstart

---

src/app/integrations/detail-page/detail.component.ts

fix(integrations): hide 'duplicate' button

---

src/app/integrations/edit-page/step-configure/data-mapper/data-mapper-host.component.ts

fix(integrations): Don't request the pom.xml for the mapper

---

src/app/integrations/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
src/app/store/integration-support.service.ts
src/config.json.example
src/config.json.minishift
src/config.json.staging
src/environments/environment.ts

feature(datamapper): Use precomputed java inspection when available

---

src/app/integrations/detail-page/detail.component.html

fix(integrations): disable history table

---

src/app/connections/create-page/review/review.component.html
src/app/connections/create-page/review/review.component.spec.ts
src/app/connections/create-page/review/review.component.ts

fix(create-connection): Remove tags from Create Connection flow

---

.mention-bot

and stop picking on Rachel
fixes #1147

feat(dev-workflow): Turn off auto reviewer assign

---

src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.ts
src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.model.ts
src/app/integrations/edit-page/step-configure/step-configure.component.html
src/app/integrations/edit-page/step-configure/step-configure.component.ts

Also takes out the placeholder text...
fixes #1158

fix(integrations): Validate the basic filter page

---

package.json
src/app/integrations/detail-page/detail.component.html
src/app/integrations/detail-page/detail.component.ts
src/app/integrations/integrations.module.ts
src/app/integrations/list-page/list-page.component.html
src/app/integrations/list-page/list-page.component.ts
src/app/store/integration-support.service.ts
yarn.lock

feat: Add integration Import/Export buttons.

---

README.md

- Add flags to syndesis-install script
- Separate out the setup section into easy-to-follow steps
- Link to more specific external instructions for env-specific installs
- Add login step

Setup section, additional info

---

src/app/integrations/list/list.component.ts

fix(integrations): Use the correct quote for this tooltip

---

src/app/app.component.html
src/app/app.component.spec.ts
src/app/app.component.ts

The linter raises an alert about an assignation being made in a conditional expression and here's the PR that addresses that.
I found some room for improvement in order to make the app more Angular-ish while I was tweaking the component so I took advantage of the commit to add a shallow refactor that takes advantage of the Angular API to ensure future compatibility with other environments (server side Angular and stuff) by monkeypatching browser-specific objects.

fix:conditional assignation replaced by check expression

---

src/tsconfig.json

fix(app): suppress typescript comments

---

src/app/common/ui-patternfly/syndesis-form-control.component.html
src/app/common/ui-patternfly/syndesis-form-control.component.ts
src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.html

fix(integrations): Bring back the trash can for the basic filter items

---

scripts/minishift-setup.sh

@chirino the `minishift-setup.sh` script didn't work for me, updated the conditional check and this seems to work fine here, can you verify?

Fix the conditional variable assignment

---

.gitignore
scripts/minishift-setup.sh

Also let's explicitly copy the file and backup any existing config.json first
fixes #1217

feat(development): Update the config.json for the development server so it's more obvious

---

package.json
scripts/pre-commit

Add a pre-commit formatting hook

---

scripts/minishift-setup.sh

Supply backup filename to -i flag

---

src/app/app.component.html
src/app/app.component.ts
src/app/connections/create-page/connection-basics/connection-basics.component.ts
src/app/connections/create-page/review/review.component.spec.ts
src/app/connections/create-page/review/review.component.ts
src/app/connections/list/list.component.html
src/app/dashboard/dashboard.component.ts
src/app/dashboard/dashboard.module.ts
src/app/integrations/edit-page/action-configure/action-configure.component.html
src/app/integrations/edit-page/action-configure/action-configure.component.ts
src/app/integrations/edit-page/action-select/action-select.component.ts
src/app/integrations/edit-page/connection-select/connection-select.component.ts
src/app/integrations/edit-page/edit-page.component.ts
src/app/integrations/edit-page/flow-view/flow-view.component.html
src/app/integrations/edit-page/flow-view/flow-view.component.spec.ts
src/app/integrations/edit-page/flow-view/flow-view.component.ts
src/app/integrations/edit-page/integration-basics/integration-basics.component.html
src/app/integrations/edit-page/integration-basics/integration-basics.component.ts
src/app/integrations/edit-page/list-actions/list-actions.component.html
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts
src/app/integrations/integrations.module.ts

Update styling for Prev/Next to look more like PF guided tour.
fix #1174

Add Remaining Tour Steps

---

src/app/app.component.html
src/app/app.component.ts
src/app/common/common.module.ts
src/app/common/ui-patternfly/notification-service.ts
src/app/connections/list/list.component.ts
src/app/integrations/components/integrationViewBase.component.ts
src/app/integrations/detail-page/detail.component.ts
src/app/integrations/list-page/list-page.component.ts
src/app/integrations/list/list.component.ts
src/app/settings/oauth-apps/oauth-app-modal.component.ts

Use an Notification[] Observable to better handle the change detection.

fix: Toast Notifications were not always showing up when called.
