package.json
src/app/+connections/connection.service.ts
src/app/+connections/library/library.component.ts
src/app/+dashboard/dashboard.component.ts
src/app/+dashboard/dashboard.e2e.ts
src/app/+dashboard/dashboard.spec.ts
src/app/app.component.ts
src/app/app.config.ts
src/app/app.module.ts

Lots of improvements need to be made here -- the API endpoint should not be hardcoded as a global string in Angular, rather, as an ENV var or even string within Webpack config files that do not get checked in, and ones that do would have a default.
Cleaned up some tests and other stuff. Minor changes.

Wire up API, hardcoded

---

src/app/+connections/create/create.component.ts
src/app/+connections/detail/detail.component.ts
src/app/+connections/edit/edit.component.ts
src/app/+connections/library/library.component.ts
src/app/+dashboard/dashboard.component.ts
src/app/app.component.ts

This was breaking `npm run build:prod` with error:
Uncaught TypeError: t.match is not a function
Same error at AngularClass/angular2-webpack-starter#958 with solution at https://github.com/AngularClass/angular2-webpack-starter/issues/958#issuecomment-249502528.
This doesn't seem to cause any problems with dev or production mode, but there may be consequences I'm totally unaware of as an ng2 & webpack n00b. Another support of removing this is in http://stackoverflow.com/questions/37178192/angular2-what-is-the-meanings-of-module-id-in-component#37178813 (lots of upvotes & accepted answer btw) which says:
If you are using webpack for bundling then you don't need  module.id in decorator. Webpack plugins auto handle (add it)  module.id in final bundle

Remove moduleId from components

---

src/app/+connections/component.service.ts
src/app/+connections/connection.model.ts
src/app/+connections/connection.service.ts
src/app/+connections/create/create.component.ts
src/app/+connections/create/create.html
src/app/+connections/create/create.scss
src/app/+connections/detail/detail.component.ts
src/app/+connections/detail/detail.html
src/app/+connections/detail/detail.scss
src/app/+connections/edit/edit.component.ts
src/app/+connections/library/library.component.ts
src/app/+connections/library/library.html
src/app/app.component.ts
src/app/app.config.ts
src/app/app.service.ts
src/app/app.spec.ts
src/app/common/service/log.ts
src/app/index.html
src/assets/scss/_common.scss

Not a ton of functionality in this PR but some key things for the demo.
- Aesthetic changes to reflect designs better across Connections user flow
- Update connection details to pull proper data (ie added breadcrumbs)
- Removed state management for now (buggy)
- Fixed minor bug where check for value is necessary before calling a split method
- Updated Connection model to reflect actual data
- Lots of cleanup, better logging
This allows the Create Connection work flow to work again.
cc @jimmidyson

Aesthetic Changes, Undo State Management & Updates to Detail View

---

src/app/common/loading/loading.component.html
src/app/common/loading/loading.component.scss
src/app/connections/list/list.component.html
src/app/integrations/list/list.component.html
src/app/templates/list/list.component.html

Because integrations list is a slightly different view (why btw)? The loader wasn't consistent with other list views.
It's subtle, but it's there - you have to look closely in these gifs to see it, have to figure out a better way to highlight changes like this without being too onerous.
Here's a before:
And an after:

Ensure loading spinner is in consistent position across lists

---

Jenkinsfile
package.json
src/app/config.service.ts
src/app/logging.ts
yarn.lock

Hopefully we can then avoid having `console.log` statements in the code, I'm as guilty as anybody.
Opted to use typescript-logging which has a nice enough API and categories.  They don't yet support changing the log level at runtime, however I've added some code that checks local storage, so to set the log level you can do:
`localStorage.logLevel = 'Trace';`
in the developer console and refresh.  Logging defaults to `Info` currently, see the interface for `LogLevel` for possible values.
I've updated a couple files that had `console.log` statements.  More info [here](https://github.com/mreuvers/typescript-logging)

Add logging API for views

---

src/app/approuting/approuting.module.ts
src/app/connections/connections-routes.module.ts
src/app/connections/connections.module.ts
src/app/integrations/create-page/configure-connection/configure-connection.component.html
src/app/integrations/create-page/configure-connection/configure-connection.component.ts
src/app/integrations/create-page/create-page.component.html
src/app/integrations/create-page/create-page.component.spec.ts
src/app/integrations/create-page/create-page.component.ts
src/app/integrations/create-page/flow-view/flow-view.component.html
src/app/integrations/create-page/flow-view/flow-view.component.ts
src/app/integrations/create-page/select-connection/select-connection.component.html
src/app/integrations/create-page/select-connection/select-connection.component.ts
src/app/integrations/integrations.module.ts
src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.spec.ts
src/app/store/entity/entity.model.ts
src/app/store/entity/entity.store.ts
src/app/store/integration/integration.model.ts
src/app/store/integration/integration.store.ts

Most work has been figuring out the routing and re-using components from connections to implement the designs.  No styling work has been done, so excuse the look of the screenshot(s), I kinda sorta started using the patternfly classes for the wizard pattern, but the design doesn't really match that pattern 100%.  Anyways, this was more about just getting elements on the page, not necessarily where they need to be :-)
And the difference between the two is subtle, look at the URL and also the `name` field at the top-left
via `Create Integration` link:
via clicking the `Edit` link from the list of integrations:
Other changes (yes, there's lots of 'em)
* refactored out routing in the connections module to use a separate routing module.
* create a 'flow-view' component
* Add wrapper pages in …

Initial work for creating/editing integrations

---

src/app/connections/list-page/list-page.component.html
src/app/connections/list-page/list-page.component.ts
src/app/connections/list/list.component.html
src/app/connections/list/list.component.ts
src/app/integrations/create-page/select-connection/select-connection.component.html
src/app/integrations/create-page/select-connection/select-connection.component.ts

This allows the create integration page to re-use the connection list for selecting connections.
Ultimately we'll need to sort having a kebab drop-down within the clickable connection element, an issue we've handled before [this way](https://github.com/redhat-ipaas/ipaas-ui/blob/master-original/src/app/%2Bconnections/library/library.component.ts#L85-L87), though maybe if we use ngClick instead to trigger the drop-down we wouldn't have to resort to that workaround.

Rework connection list to trigger a selected event so parent component can control what to do

---

src/app/integrations/create-page/configure-connection/configure-connection.component.html
src/app/integrations/create-page/configure-connection/configure-connection.component.ts
src/app/integrations/create-page/create-page.component.html
src/app/integrations/create-page/create-page.component.spec.ts
src/app/integrations/create-page/create-page.component.ts
src/app/integrations/create-page/current-flow.service.ts
src/app/integrations/create-page/flow-view/flow-view.component.html
src/app/integrations/create-page/flow-view/flow-view.component.scss
src/app/integrations/create-page/flow-view/flow-view.component.ts
src/app/integrations/create-page/select-connection/select-connection.component.ts
src/app/integrations/integrations.module.ts

Basically at least lets you click though some of the flow, i.e. picking a connection, viewing what ought to be the configuration form, then picking the end connection etc.
More work to do, going to bring in [this library](https://github.com/udos86/ng2-dynamic-forms) to render the configuration form for the connection which will replace the json in the second page.
More validation between steps is needed too, side-bar should eventually start being more dynamic.
Also still have to implement saving the integration.  Anyhoo, screencast of how it's looking:

Add a service for the current integration, use events to communicate between views

---

protractor.conf.js

According to lathonez/clicker#205 there was api break in SpecReporter 3.
With this change I'm able to run `yarn e2e`, but the tests will fail anyway, because browser is redirected to github for oAuth.

[relates #52] Fix SpecReporter require in protractor config

---

src/app/integrations/create-page/configure-connection/configure-connection.component.html
src/app/integrations/create-page/create-page.component.html
src/app/integrations/create-page/create-page.component.ts
src/app/integrations/create-page/current-flow.service.ts

This PR ensures the page title in the integration editor matches the designs as you go through the wizard.
Also added the back button, though currently you can't go back once you've set the start connection currently.  Just shhh don't tell anybody that.
Also added chevrons and s/Finish/Create/ per the design.

Dynamically set page title, add back button, tweak connection selection

---

src/app/integrations/create-page/create-page.component.html
src/app/integrations/create-page/create-page.component.scss
src/app/integrations/create-page/current-flow.service.ts
src/app/integrations/create-page/flow-view/flow-view.component.html
src/app/integrations/create-page/flow-view/flow-view.component.scss
src/app/integrations/create-page/flow-view/flow-view.component.ts
src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.scss

Changes:
- Aesthetic changes for Create an Integration view to reflect designs more closely. (e.g. fix layout issue, sidebar)
- Fix lint error caused by previous PR merge w/ trailing whitespace.
Again, apologies for not squishing commits- it's crunch time. :)
In Progress (next PR, all minor tweaks):
- Center + icon in cube-line design on left-hand side
- Integration List improvements
- Connection Detail improvements
Low priority (may not happen for the demo):
- Automatically collapse the sidebar when in the Create Integration view, otherwise the layout is too wide and you can scroll to the right (for the demo we may have to manually collapse it).
- Look into issue where child components don't inherit CSS from parent components located in different modules.
- I might adjust the bottom bar …

Create an Integration UI Fixes

---

src/app/integrations/create-page/create-page.component.ts
src/app/integrations/create-page/current-flow.service.ts
src/app/integrations/create-page/flow-view/flow-view.component.html
src/app/integrations/create-page/flow-view/flow-view.component.scss
src/app/integrations/create-page/flow-view/flow-view.component.ts
src/app/integrations/create-page/select-connection/select-connection.component.ts
src/app/store/entity/entity.store.ts

This makes the sidebar reflect the state of the integration as the user selects connections, the expanding items are closed and the icon available on the connection replaces the cube.

Reflect integration state in the flow-view component

---

src/app/app.component.html
src/app/app.component.scss
src/app/integrations/list-toolbar/list-toolbar.component.html
src/app/integrations/list-toolbar/list-toolbar.component.scss
src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.scss

Changes:
- Fixed annoying sidebar text being bold and underlined when you click on it and hover away.
- Aesthetic changes in navigation bar, toolbar, username and icon.
- Changed list from PatternFly's nested divisions to BootStrap's column grid for each row in the list; much nicer to work with and to style.
- Other UI tweaks, particularly for the Integrations List view.
Sheck it out..
Design is [here](https://redhat.invisionapp.com/share/VQ8UZ7PCE#/210535233_Integration-list) for reference.
@jimmidyson Let me know if you want me to enable those tabs; they are very easy to style to look like the designs. I'd just need to know if the API supports this type of filtering easily, or if I need to do it from the UI (or should just hold off, etc). For now I've commented them out but left them …

Integration List, Sidebar & Navigation Fixes

---

src/app/integrations/create-page/create-page.component.spec.ts
src/app/integrations/create-page/current-flow.service.spec.ts
src/app/integrations/create-page/current-flow.service.ts
src/app/integrations/create-page/flow-view/flow-view-step.component.html
src/app/integrations/create-page/flow-view/flow-view-step.component.scss
src/app/integrations/create-page/flow-view/flow-view-step.component.ts
src/app/integrations/create-page/flow-view/flow-view.component.html
src/app/integrations/create-page/flow-view/flow-view.component.scss
src/app/integrations/create-page/flow-view/flow-view.component.spec.ts
src/app/integrations/create-page/flow-view/flow-view.component.ts
src/app/integrations/integrations.module.ts

Wanted to first off get the flow view thingie to handle more than 2 steps :-)
I reorganized the elements a bit (kept the old markup commented out for now) to use an `*ngFor` for the steps in the integration.  I haven't handled the line that connects the icons and left it out for now, I think we'll need to figure out a good generic approach to that as we'll quickly start getting more complicated flows to visualize.  Anyhoo, screenshot:

[WIP] Use a proper ngFor in the flow view, use flex parent to lay out child elements

---

src/app/app.module.ts
src/app/common/common.module.ts
src/app/connections/view-page/view-page.component.spec.ts
src/app/connections/view-wrapper/view-wrapper.component.spec.ts
src/app/integrations/create-page/current-flow.service.spec.ts
src/app/integrations/create-page/flow-view/flow-view.component.spec.ts
src/app/store/connection/connection.service.ts
src/app/store/connection/connection.store.ts
src/app/store/entity/entity.store.ts
src/app/store/entity/events.service.ts
src/app/store/entity/rest.service.ts
src/app/store/integration/integration.service.ts
src/app/store/integration/integration.store.ts
src/app/store/store.module.ts
src/app/store/template/template.service.ts
src/app/store/template/template.store.ts
src/typings.d.ts
yarn.lock

Works in conjunction with the following PR:
https://github.com/redhat-ipaas/ipaas-rest/pull/115

Use the new Server Side Event support in ipaas-rest to automatically reload updated entity lists.

---

scripts/templates/typescript-class.mustache
src/app/integrations/create-page/current-flow.service.ts
src/app/model.ts
src/app/store/entity/entity.store.ts
src/app/store/integration/integration.store.ts

This updates the code generator so it generates a type factory class for all the types, so you don't have to do this in your code:
```
const myThingy = <Integration> {};
```
Instead you can do:
```
const myThingy = TypeFactory.createIntegration();
```
mostly will be good for implementing `newInstance()` functions for stores.  I also added an `updateOrCreate` function to the base store so every component/service that creates stuff doesn't have to do the same, the implementation makes the assumption that we don't set `id` properties when we create objects client-side.
**One thing to note: **  Adding the creation functions or type factory class to the generated code seems to have triggered some weird typescript bug, so you'll see these warnings with `yarn run start`:
```
WARNING in …
```

Add a type factory to the model and an updateOrCreate function to the store

---

package.json
src/app/app.module.ts
yarn.lock

I'd like to merge this ASAP but this will break any local use due to the single
redirect policy for GitHub OAuth apps. Would appreciate help coming to right
solution so we don't break everyone.
3 potential solutions:
1. Each dev have their own oauth app pointing at whatever local redirect URL they
want. This is my preferred option to be honest as it's most flexible but is also
hardest to set up for new contributors.
2. Each dev use the same URL locally and a single oauth application. This would
work but coming up with a URL that works for everyone might prove tricky. Also
have to share oauth app secrets somehow. Not good for new contributors perhaps.
3. Set up a @chirino's redirector that can be used to redirect to local app. Not sure I like
this as it goes against normal oauth flow.
We …

Two phase OAuth flow to support OpenShift and GitHub

---

src/app/common/common.module.ts
src/app/connections/connections.module.ts
src/app/connections/create-page/configure-fields/configure-fields.component.html
src/app/connections/create-page/configure-fields/configure-fields.component.ts
src/app/connections/create-page/connection-basics/connection-basics.component.html
src/app/connections/create-page/review/review.component.html
src/app/connections/create-page/review/review.component.ts
src/app/connections/view-page/view-page.component.spec.ts
src/app/connections/view-wrapper/view-wrapper.component.spec.ts
src/app/connections/view/view.component.html
src/app/connections/view/view.component.spec.ts
src/app/connections/view/view.component.ts

This gets page 2 of the create connection flow going.
No data from the form is saved yet, probably not going to happen until we've ironed out the persistence.  Also all pages in the wizard require styling work, hoping to get that going tomorrow.
Obligatory screenshot:

Create connection flow step 2

---

src/app/model.ts
src/app/store/action/action.service.ts
src/app/store/action/action.store.ts
src/app/store/store.module.ts

Adds in the new action type and associated restangular service/store, pointing at the top-level 'actions' API

Regen models, add action service/store

---

src/app/integrations/edit-page/edit-page.component.ts
src/app/integrations/edit-page/flow-view/flow-view.component.html
src/app/integrations/edit-page/flow-view/flow-view.component.ts
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts

This adds the links that let you add a step or connection to a flow.  They only show up on this page.  I think BTW that the buttons in the main view make no sense as there's no context to figure out where a step/connection should be added in the flow, unlike the inlined links.  Something to discuss with UX.

Add links to insert steps/connections

---

src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.ts

Add methods for toast notifications and modal confirmations for activating and deactivating an integration.
There is currently an issue where it selects the wrong modal, and also the toast notifications need to be styled, but, hey, it's a start:

Add Toast notification and modal for deactivation and activation

---

src/app/integrations/edit-page/current-flow.service.ts
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.html
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts
src/app/integrations/edit-page/step-configure/step-configure.component.ts

Also for the moment add a separate 'Save' and 'Publish' button so you can save an integration as activated or deactivated from the editor at least.

Fix #281, missed a spot saving configuredProperties for steps vs connections

---

src/app/integrations/edit-page/flow-view/flow-view-step.component.scss
src/app/integrations/edit-page/flow-view/flow-view.component.html
src/app/integrations/edit-page/flow-view/flow-view.component.scss
src/app/integrations/edit-page/integration-basics/integration-basics.component.html
src/app/integrations/edit-page/integration-basics/integration-basics.component.scss
src/app/integrations/edit-page/integration-basics/integration-basics.component.ts

Minor changes to update the form view in Create Integration:
Made the `min-height` adjustable for a CSS class because I might need it for fixing the issue with the `step-line` class in a future PR.
Next PR will remove the icons from Steps and make minor changes to the Integration List (responsiveness), add deleting modal & toast notifications (re-add them), and support activation/deactivation.

Create int changes

---

src/app/integrations/edit-page/integration-basics/integration-basics.component.html
src/app/integrations/edit-page/integration-basics/integration-basics.component.ts
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts

At least until we get auto-naming implemented.  So now you get prompted for the name if you haven't set it before saving the integration.

Make the integration basics page only show up if the integration isn't named

---

src/app/integrations/edit-page/action-configure/action-configure.component.ts
src/app/integrations/edit-page/connection-select/connection-select.component.ts
src/app/integrations/edit-page/edit-page.component.html
src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/edit-page/step-configure/step-configure.component.ts

This hides the 'Choose a Connection' and 'Choose an action' links on the left after the user has gone through those pages and defaults the parent item (connection or step name) to link to the 'Configure' page containing the form instead.
@kcbabo @chirino FYI

Hide 'choose connection/action/step' once the user has gone through those pages

---

src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/edit-page/flow-view/flow-view-step.component.scss
src/app/integrations/edit-page/flow-view/flow-view-step.component.ts
src/app/integrations/edit-page/flow-view/flow-view.component.html
src/app/integrations/edit-page/flow-view/flow-view.component.scss
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.html
src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts

- Add space between start and finish icons, require that line take up the full height of the division as it grows and shrinks, with a minimum height of 200px always being required.
- Refactor SCSS for `flow-view-step.component.scss` to accommodate for active/inactive and complete/incomplete state classes.
- Add method (not functional, but that's for a separate PR) to determine whether section is complete or incomplete.
- Fix bug that was causing icons to all have `inactive` states. re #305
- 'Add Step' and 'Add Connection' buttons on first-time landing page when saving or adding a step are functional, though redirect does not work properly. re #314 
- Determine when a Step is complete and assign appropriate class.
- Force tooltip to remain open on first time user is prompted to add a step …

Create Integration Changes

---

src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/edit-page/flow-view/flow-view-step.component.scss
src/app/integrations/edit-page/flow-view/flow-view-step.component.ts
src/app/integrations/edit-page/flow-view/flow-view.component.html
src/app/integrations/edit-page/flow-view/flow-view.component.scss
src/app/integrations/edit-page/flow-view/flow-view.component.ts

This also reduces the height of steps so there's less vertical used by a flow, also tweaks some highlight behavior.

Fix #313 just check if there's middle components, if not then we show the popover

---

e2e/data/users.example.json

Just small typo fix in `users.json.example` to link the narrative's Camilla to e2e's Camilla.
cc @jludvice @kahboom

Fix typo in user's alias

---

src/app/integrations/edit-page/flow-view/flow-view-step.component.scss

border color defined in `.complete` and `.incomplete` classes was overriding color specified by `.active` and `.inactive` css classes.
This way 
- completed/incompleted icon in the middle has black/gray color
- active inactive round is blue / gray
Is this change ok @kahboom ?

[relates #295] Fix active inactive round box

---

src/app/app.module.ts
src/app/config.service.ts
src/app/integrations/edit-page/step-configure/data.mapper.example.host.component.ts
src/config.json.example
src/environments/environment.ts

This makes the settings in `config.json` take precedence for the data mapper endpoints.  So you'll need a `config.json` that looks like this for staging:
```
{
"apiEndpoint": "https://ipaas-staging.b6ff.rh-idev.openshiftapps.com/api/v1",
"title": "Red Hat iPaaS",
"datamapper": {
"baseJavaServiceUrl": "https://ipaas-staging.b6ff.rh-idev.openshiftapps.com/v2/atlas/java/",
"baseMappingServiceUrl": "https://ipaas-staging.b6ff.rh-idev.openshiftapps.com/v2/atlas/"
},
"oauth": {
"clientId": "ipaas-ui",
"scopes": [],
"oidc": true,
"hybrid": true,
"issuer": "https://ipaas-staging.b6ff.rh-idev.openshiftapps.com/auth/realms/ipaas"
}
}
```
@jimmidyson how does this get picked up in the staging instance?  Want to be sure we get that working too but I couldn't tell from the CI config.
Probably worth …

Externalize the datamapper config

---

e2e-xvfb.sh
e2e/Readme.md
e2e/conf/protractor.base.conf.js
package.json

Related to #93. This PR adds possibility to execute e2e tests from Docker container.

Add cmd e2e:xvfb to execute e2e tests in container

---

src/app/integrations/edit-page/step-configure/data.mapper.example.host.component.ts

Just a little fix that ensures the data mapper shows up on the page, noticed when investigating updating the component to the latest commit.

Run the change detector after we initialize the mapper component

---

src/app/integrations/edit-page/flow-view/flow-view-step.component.scss
src/app/integrations/edit-page/flow-view/flow-view.component.scss

- Fixed sidebar donut thing-y in the Create an Integration sidebar.
- Darkened the background of the grayed out menu items on the left hand sidebar.
- Darkened the entire diagram / progress line on the left hand side.
- Change hover state background for list of Steps to be blue instead of gray.
- Change pointer for each step.

Create Integration: Sidebar Fixes

---

src/app/connections/create-page/create-page.component.scss
src/app/connections/view-toolbar/view-toolbar.component.html

Not sure what happened, but in staging it looks like this:
This fix, well, fixes it to look like this:
Also, this PR fixes #441 , where the Home link in the breadcrumbs for the Connection Detail page results in an error in the browser console and doesn't work.

Fix toolbar margin in Create Connection & broken Home link

---

src/app/integrations/list/list.component.html
src/app/integrations/list/list.component.scss
src/app/integrations/list/list.component.ts

- Remove the toggle and ability to change status from status label.
- Re-add labels.
- Hide 'Uses' column.
- Fix actions in dropdown kebab based on `currentStatus`.
NOTE: We'll need to re-assess the conditions for actions using a diagram. I'll work on that throughout the week.

Rm Toggle, Add Labels

---

e2e/app.po.ts
e2e/common/common.steps.ts
e2e/common/common.ts
e2e/connections/connections.feature
e2e/login/login.feature
e2e/login/login.po.ts

Related to #513. I've tried to implement submitting details for first time visit page.
It would be better to have details in gherkin data table, but I wasn't able to get it working properly, probably my silly mistake. I think we can improve it later and go on just with opinionated defaults right now. 
Where it gets interesting is [this part](https://github.com/redhat-ipaas/ipaas-ui/compare/master...dsimansk:e2e-fixes?expand=1#diff-6fe650a8e21fe8d744c835bf070922f3R152). Would it be better to react on `waitForAngularEnabled` error and kick-in filling the form afterwards?

[E2E] Handle Keycloak first time visit page in E2E tests

---

src/app/connections/view-toolbar/view-toolbar.component.scss
src/app/connections/view/view.component.html
src/app/connections/view/view.component.scss
src/app/dashboard/integrations.component.html
src/app/dashboard/integrations.component.scss
src/app/integrations/list/list.component.html

- Dashboard: Spaced out column distribution of Recent Updates and Top 5 Integrations widgets.
- Dashboard: Hid 'uses' column, as we will not be using it.
- Dashboard: Cursor change to `pointer` for Recent Updates, as these are now actionable rows.
- Dashboard: Update tooltip on Integration Board chart to overlay the total Integration count.
- Connection Detail: Updated Tags to use `labels` rather than badges. Spaced them out.
- Connection Detail: Entire page, including toolbar, should now use `cursor: default` unless it's an anchor, to make it appear more polished and final.
- Integration List: Distributed columns more evenly to give additional space to names.
Column spacing for Recent Updates and Top 5 Integrations widgets.
**Before: Swallowed up text**
**After: No more swallowing!**

Aesthetic changes in Dashboard, Connection Detail, and Integration List

---

e2e/app.po.ts
e2e/login/login.po.ts

On a clean deployment, there's yet another `Authorize Access` (ServiceAccount asking to access user info) page that needs to be submitted. This PR should handle this page.
Also I've added a bit `waitForAngular()` magic [here](https://github.com/syndesisio/syndesis-ui/compare/master...dsimansk:e2e-fixes?expand=1#diff-6fe650a8e21fe8d744c835bf070922f3R133), to improve stability.

e2e: add handler for SA Authorize access page

---

README.md
package.json
yarn.lock

Add commitizen support, can now commit via `yarn commit` instead of `git commit`
Fixes #590

chore(tooling): Add commitizen support

---

package.json

The last pull request from this fork added initialization flags for adding debug logging and adding mock source/target documents. This PR updates the data mapper library dependency pointer to the latest commit on that project with api changes to accommodate these features.

Update data mapper dependency url for latest initialization api changes.

---

README.md
src/app/integrations/edit-page/current-flow.service.ts
src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.html
src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.scss
src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.ts
src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.model.ts
src/app/integrations/edit-page/step-configure/filter-steps/filter.interface.ts
src/app/integrations/edit-page/step-configure/step-configure.component.html
src/app/integrations/edit-page/step-configure/step-configure.component.ts
src/app/integrations/edit-page/step-select/step-select.component.ts
src/app/integrations/integrations.module.ts
src/app/store/step/step.store.ts

Initial run-through of the basic filter implementation for integrations.
- Add basic filter component, interface, model, styling, HTML.
- Update parent step-configure component and HTML to communicate with filter sub-component.
- Update `step.store.ts` to include filter in list of available steps when creating integrations.
- Update README with some commitizen tips.

Filter Step (Basic) - Initial Run-Through

---

src/app/integrations/edit-page/flow-view/flow-view-step.component.ts

Tooltip over the icon area should only show up for connections and only if there's a connection name
set
relates to #690

fix(integrations): Add more restrictions for showing the tooltip

---

src/app/app.module.ts
src/app/common/can-deactivate-guard.service.ts
src/app/connections/connections-routes.module.ts
src/app/connections/connections.module.ts
src/app/connections/create-page/cancel.component.ts
src/app/connections/create-page/configure-fields/configure-fields.component.ts
src/app/connections/create-page/connection-basics/connection-basics.component.ts
src/app/connections/create-page/create-page.component.ts
src/app/connections/create-page/review/review.component.ts

I'm using window.confirm to show a confirmation dialog to the user. To show a modal, we need to implement a modal service that shows the modal dialog and returns a promise with the result (yes/no).

feat(Connections): Confirm before leaving 'new connection' pages

---

src/app/integrations/edit-page/step-select/step-select.component.html
src/app/integrations/edit-page/step-select/step-select.component.ts
src/app/integrations/edit-page/step-select/step-visible.pipe.ts
src/app/integrations/integrations.module.ts
src/app/store/step/step.store.ts

If the integration has a start or end action that doesn't have a data shape, prevent the data mapper
from being selected.
fixes #562

feat(integrations): hide data mapper if the integration is missing types

---

src/app/integrations/edit-page/current-flow.service.ts
src/app/integrations/edit-page/flow-view/flow-view-step.component.html
src/app/integrations/edit-page/flow-view/flow-view-step.component.scss
src/app/integrations/edit-page/flow-view/flow-view-step.component.ts

Ensures the user has to complete a flow of pages for a connection or step before being able to click
elsewhere in the integration.  Also hides the trash icons for steps and connections unles s the user
is on the save or add step page.
fixes #696, fixes #723

feat(integrations): Tighten up editor navigation

---

src/app/connections/create-page/configure-fields/configure-fields.component.ts
src/app/connections/create-page/connection-basics/connection-basics.component.ts
src/app/connections/create-page/create-page.component.ts
src/app/connections/create-page/current-connection.ts
src/app/connections/create-page/review/review.component.ts
src/app/store/connector/connector.service.ts
src/app/store/entity/entity.store.ts

Apply hacksaw to current connection service
relates to #556 
@zregvart FYI, will merge this assuming it checks out in CI be curious to see how this works on staging actually...

feat(connections): Engage sledgehammer

---

src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.ts
src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.model.ts

validate before parsing JSON just to be on the safe side
@rhuss FYI, turns out there was another change that introduced the JSON parsing, this fix appears to load and save to the in-memory integration fine.

fix(integrations): Basic filter fixes

---

src/config.json.staging

Adds `config.json.staging` template configured for development against
the staging on Openshift Online.
Fixes #767

feat(development): Adds configuration for staging

---

package.json
src/app/integrations/edit-page/flow-view/flow-view.component.html
yarn.lock

Updates `ngx-bootstrap` to 1.9.1
fixes #824 
@syndesisio/design-ux Run `yarn install` after pulling once this is merged...

fix(integrations): pass along context so we keep the position

---

src/app/integrations/edit-page/step-configure/data-mapper/data-mapper-host.component.ts

Fixes #860
Problem was that the ConfigService instance passed in as a constructor arg is not populated with src/config.json. Once remove this line the shared instance populated with config.json is properly passed in and datamapper url respects them.

fix(datamapper): src/config.json is ignored for datamapper URL

---

src/app/integrations/edit-page/step-configure/data-mapper/data-mapper-host.component.ts

For datashapes with kind=json it is expected that the `specification`
field contains JSON schema as string. This provides the datamapper with
the value therein.
Fixes #947

chore: Send JSON schema to mapper

---

src/app/app.component.html
src/app/app.component.ts
src/app/approuting/approuting.module.ts
src/app/setup/github-oauth.component.html
src/app/setup/github-oauth.component.scss
src/app/setup/github-oauth.component.ts
src/app/setup/setup-root.component.ts
src/app/setup/setup.module.ts

Hey, it's a start. Need to add in plumbing, styling, logic, tests, docs, lots more. This just creates a new module and component, adds the route, HTML.
Outstanding:
- Programmatically collapse the sidebar and navbar.
- Alternatively, or in addition, add `ngIf` to check for flag set in the API that determines whether or not the user is a first time user to determine whether or not to show the sidebar and navbar.
- Add in plumbing with API once available.
- Check for client ID and secret to determine what to show the user (low priority, probably not for TP1 as we should just be worrying about users that have not connected their GH accounts).
- Styling and closer reflection of the designs provided by UXD.

feat(github-oauth): Setup with GitHub OAuth as part of FTUE

---

src/app/app.component.html

Will add in the About link in the dropdown once we have the content for the modal. cc @dongniwang

feat(docs): Add link to external Fuse docs and icon

---

src/app/connections/common/configuration/configuration.service.ts

Adds `sql-stored-connector` to the list of connectors that we validate.

chore: enable validations for SQL stored connector

---

angular-cli.json
src/app/common/ui-patternfly/syndesis-combobox.directive.ts
src/app/common/ui-patternfly/syndesis-form-control.component.html
src/app/common/ui-patternfly/ui-patternfly.module.ts

Adds a `syndesisCombobox` directive to apply combobox from Patternfly
to <select> elements and uses that for dynamic forms.

chore: uses patternfly combo box for select element

---

README.md
package.json
scripts/minishift-setup.sh
yarn.lock

This allows you to run in dev mode even when your using an oauth-proxy in front of the UI service.

Updating the developer mode getting started instructions so that it works via redirecting the syndesis-ui service deployed in minishift.

---

pom.xml

- Remove NPM version as its supplied with node (see frontend plugin isProvided property)
- Downgrade to 6.11.5 (Current LTS)
It might be worth upgrading to Node 8.x when LTS is announced? it looks like it will be a LTS version

Prod tooling changes

---

src/app/integrations/edit-page/edit-page.component.ts
src/app/integrations/edit-page/flow-view/flow-view.component.ts
src/app/integrations/edit-page/step-configure/step-configure.component.ts

@kahboom I'm thinking maybe it's worth waiting to intialize the tour until we've loaded the integration, I've moved that block of code where that happens, probably also should make it conditional, as the tour probably shouldn't be started if it's a previously loaded integration, i.e. it only has an ID if we're loading a previously created integration, if it's a new integration then there's no ID.
fixes #1194

fix(integrations): Comment out the guided tour block for now in the integration editor
